export const products = [
  {
    id: 1,
    title: "MSI GT 710 2GD3H LP 2GB DDR3 Gaming Graphics Card",
    price: 	5300,
    category: "Graphics Card",
    description: "High-performance graphics card for gaming.",
    image: "/src/assets/Graphic1.jpg",
  },
  {
    id: 2,
    title: "Gigabyte GT 710 2GB DDR3 Graphics Card",
    price: 	5900,
    category: "Graphics Card",
    description: "Reliable graphics card with great performance.",
    image: "/src/assets/Graphic2.png",
  },
  {
    id: 3,
    title: "Palit GeForce GT 1030 2GB DDR4 Graphics Card with No Warranty",
    price: 6500,
    category: "Graphics Card",
    description: "Compact graphics card suitable for various setups.",
    image: "/src/assets/graphic3.jpg",
  },
  {
    id: 4,
    title: "Gaming Laptop",
    price: 1200,
    category: "Laptop",
    description: "Powerful gaming laptop with high refresh rate display.",
    image: "/src/assets/laptop1.webp",
  },
  {
    id: 5,
    title: "Business Laptop",
    price: 900,
    category: "Laptop",
    description: "Sleek laptop designed for productivity and business tasks.",
    image: "/src/assets/laptop2.webp",
  },
  {
    id: 6,
    title: "Ultrabook",
    price: 1500,
    category: "Laptop",
    description: "Lightweight ultrabook with long battery life.",
    image: "/src/assets/laptop3.webp",
  },
  {
    id: 7,
    title: "4K Monitor",
    price: 400,
    category: "Monitor",
    description: "Stunning 4K monitor for immersive viewing experience.",
    image: "/src/assets/laptop4.webp",
  },
  {
    id: 8,
    title: "Curved Gaming Monitor",
    price: 350,
    category: "Monitor",
    description: "Curved monitor with high refresh rate for gaming.",
    image: "/src/assets/Second.webp",
  },
  {
    id: 9,
    title: "Portable Monitor",
    price: 200,
    category: "Monitor",
    description: "Lightweight portable monitor for on-the-go productivity.",
    image: "/src/assets/Second.webp",
  },
  {
    id: 10,
    title: "First Laptop",
    price: 1100,
    category: "Laptop",
    description: "All-rounder laptop for work and play.",
    image: "/src/assets/laptop3.webp",
  },
  {
    id: 11,
    title: "Second Laptop",
    price: 950,
    category: "Laptop",
    description: "Affordable laptop with decent performance.",
    image: "/src/assets/laptop3.webp",
  },
  {
    id: 12,
    title: "High Refresh Rate Monitor",
    price: 450,
    category: "Monitor",
    description: "Monitor with high refresh rate for smoother gameplay.",
    image: "/src/assets/Second.webp",
  },
  {
    id: 13,
    title: "Lightweight Laptop",
    price: 800,
    category: "Laptop",
    description: "Thin and light laptop for easy portability.",
    image: "/src/assets/laptop3.webp",
  },
  {
    id: 14,
    title: "Gaming Monitor",
    price: 300,
    category: "Monitor",
    description: "Monitor specifically designed for gaming.",
    image: "/src/assets/Second.webp",
  },
  {
    id: 15,
    title: "Professional Monitor",
    price: 600,
    category: "Monitor",
    description: "High-quality monitor for graphic design and video editing.",
    image: "/src/assets/Second.webp",
  },
  {
    id: 16,
    title: "Affordable Graphics Card",
    price: 80,
    category: "Graphics Card",
    description: "Budget-friendly graphics card for casual gaming.",
    image: "/src/assets/Second.webp",
  },
  {
    id: 17,
    title: "High-End Graphics Card",
    price: 200,
    category: "Graphics Card",
    description: "Top-tier graphics card for enthusiasts.",
    image: "/src/assets/Second.webp",
  },
  {
    id: 18,
    title: "Office Monitor",
    price: 250,
    category: "Monitor",
    description: "Reliable monitor for office use with good color accuracy.",
    image: "/src/assets/Second.webp",
  },
  {
    id: 19,
    title: "Gaming Laptop Pro",
    price: 1800,
    category: "Laptop",
    description: "Ultimate gaming laptop for professional gamers.",
    image: "/src/assets/laptop1.webp",
  },
  {
    id: 20,
    title: "2-in-1 Laptop",
    price: 1300,
    category: "Laptop",
    description: "Versatile 2-in-1 laptop with detachable keyboard.",
    image: "/src/assets/laptop2.webp",
  },
];
